<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.10.1</Version>
    <AssemblyVersion>1.10.1.0</AssemblyVersion>
    <FileVersion>1.10.1.0</FileVersion>
    <AssemblyName>AcadBatchPlot</AssemblyName>
    <RootNamespace>ZwcadBatchPlot</RootNamespace>
    <DefineConstants>$(DefineConstants);AUTOCAD;LEGACY_ACAD</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin-acad2017\</OutputPath>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\Common\**\*.cs" />
    <Compile Include="src\AutoCAD\**\*.cs" />
    <Compile Include="src\PianNoCN\**\*.cs" />
    <EmbeddedResource Include="src\AutoCAD\**\*.resx" />
    <None Remove="src\AutoCAD\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FileTools\**\*.cs" />
    <EmbeddedResource Remove="FileTools\**\*" />
    <None Remove="FileTools\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="resources\acad\Plotters\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Plotters\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="AutoCAD.NET" Version="21.0.1">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="SharpZipLib" Version="0.86.0" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>
</Project>
