<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.12.1</Version>
    <AssemblyVersion>1.11.2.0</AssemblyVersion>
    <FileVersion>1.11.2.0</FileVersion>
    <AssemblyName>AcadBatchPlot</AssemblyName>
    <RootNamespace>ZwcadBatchPlot</RootNamespace>
    <DefineConstants>$(DefineConstants);AUTOCAD;ACAD2013</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin-acad2013\</OutputPath>
    <GenerateResourceUsePreserializedResources>false</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\Common\**\*.cs" />
    <Compile Include="src\AutoCAD\**\*.cs" />
    <EmbeddedResource Include="src\AutoCAD\**\*.resx" />

    <ProjectReference Include="src\PianNoCN\PianNoCN.csproj" />
    <None Remove="src\AutoCAD\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FileTools\**\*.cs" />
    <Compile Remove="lib\**\*.cs" />
    <Compile Remove="local-artifacts\**\*.cs" />
    <Compile Remove="tests\**\*.cs" />
    <Compile Remove="tmp\**\*.cs" />
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="obj*\**\*.cs" />
    <Compile Remove="_tmp*\**\*.cs" />
    <Compile Remove="._tmp*\**\*.cs" />
    <EmbeddedResource Remove="FileTools\**\*" />
    <EmbeddedResource Remove="lib\**\*" />
    <EmbeddedResource Remove="local-artifacts\**\*" />
    <EmbeddedResource Remove="tests\**\*" />
    <EmbeddedResource Remove="tmp\**\*" />
    <EmbeddedResource Remove="obj\**\*" />
    <EmbeddedResource Remove="obj*\**\*" />
    <EmbeddedResource Remove="_tmp*\**\*" />
    <EmbeddedResource Remove="._tmp*\**\*" />
    <None Remove="FileTools\**\*" />
    <None Remove="lib\**\*" />
    <None Remove="local-artifacts\**\*" />
    <None Remove="tests\**\*" />
    <None Remove="tmp\**\*" />
    <None Remove="obj\**\*" />
    <None Remove="obj*\**\*" />
    <None Remove="_tmp*\**\*" />
    <None Remove="._tmp*\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="resources\acad\Plotters\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Plotters\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="AutoCAD.NET" Version="19.0.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="PDFsharp" Version="1.50.5147" />
    <PackageReference Include="SharpZipLib" Version="1.3.3" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>
</Project>
