<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ZwManaged">
      <HintPath>C:\Program Files\ZWSOFT\ZWCAD Enterprise\ZwManaged.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ZwDatabaseMgd">
      <HintPath>C:\Program Files\ZWSOFT\ZWCAD Enterprise\ZwDatabaseMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\Program Files\ZWSOFT\ZWCAD Enterprise\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
