<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.5.2</Version>
    <AssemblyVersion>1.5.2.0</AssemblyVersion>
    <FileVersion>1.5.2.0</FileVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FileTools\**\*.cs" />
    <Compile Remove="src_acad\**\*.cs" />
    <Compile Remove="local-artifacts\**\*.cs" />
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="obj*\**\*.cs" />
    <Compile Remove="_tmp*\**\*.cs" />
    <Compile Remove="._tmp*\**\*.cs" />
    <EmbeddedResource Remove="FileTools\**\*" />
    <EmbeddedResource Remove="src_acad\**\*" />
    <EmbeddedResource Remove="local-artifacts\**\*" />
    <EmbeddedResource Remove="obj\**\*" />
    <EmbeddedResource Remove="obj*\**\*" />
    <EmbeddedResource Remove="_tmp*\**\*" />
    <EmbeddedResource Remove="._tmp*\**\*" />
    <None Remove="FileTools\**\*" />
    <None Remove="src_acad\**\*" />
    <None Remove="local-artifacts\**\*" />
    <None Remove="obj\**\*" />
    <None Remove="obj*\**\*" />
    <None Remove="_tmp*\**\*" />
    <None Remove="._tmp*\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ZwManaged">
      <HintPath>C:\Program Files\ZWSOFT\ZWCAD Enterprise\ZwManaged.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ZwDatabaseMgd">
      <HintPath>C:\Program Files\ZWSOFT\ZWCAD Enterprise\ZwDatabaseMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\Program Files\ZWSOFT\ZWCAD Enterprise\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2535.41" />
    <PackageReference Include="PDFsharp" Version="1.50.5147" />
  </ItemGroup>
</Project>
